######################################################################
# Automatically generated by qmake (2.01a) dim. août 29 00:34:38 2010
######################################################################

TEMPLATE = app
TARGET = updater
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../Multiuso/Multiuso.h
SOURCES += main.cpp
