######################################################################
# Automatically generated by qmake (2.01a) jeu. mars 11 20:23:58 2010
######################################################################

TEMPLATE = app
CONFIG += release
TARGET = Updater
win32:RC_FILE += ressources/windows.rc
DEPENDPATH += . ressources
INCLUDEPATH += .

# Input
HEADERS += FenPrincipale.h ../Multiuso/Multiuso.h
SOURCES += FenPrincipale.cpp main.cpp
RESOURCES += ressources/icones.qrc ressources/mime.qrc
